[package]
name = "os_thing"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9" # KEEP IT 0.9
volatile = "0.2.6" # KEEP IT 0.2.6
spin = "0.10.0"  
x86_64 = "0.14.2"  # KEEP IT 0.14.2
uart_16550 = "0.4.0"
pic8259 = "0.11.0"
pc-keyboard = "0.8.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]


[[bin]]
path = "src/main.rs"
name = "os_thing"
test = true
bench = false

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", "-display", "none"] # for clean way to exist QEMU while testing test build :D AND for serial output of test result stuff
test-success-exit-code = 33 # our exit code: 33 | cargo's test exit code must be 0... we map it like this so we not get unintended behaviour
test-timeout = 300 


# TEST STUFF

[[test]]
name = "stack_overflow"
harness = false
